### ISSUE TITLE
Adding To-Do List

### ISSUE THREAD

**Issue by 03nix** [maltehi/outlook-taskboard#5]
maltehi,
I've tried using evrenvarol's fix to add the To-Do List items to include any flagged emails. I haven't been able to have success adding his code to yours. Could you see what my problem is and potentially add this feature to the taskboard?

everenvarol's fix:
https://github.com/evrenvarol/outlook-taskboard/pull/36/commits/011f81432572c6d022140583d8c6889c878c38aa
https://github.com/evrenvarol/outlook-taskboard/pull/36/commits/a3da5be2657799a9d1529e4bf0906c99bf7061e1

My attempt:
[app To-Do Items fix attempt.txt](https://github.com/maltehi/outlook-taskboard/files/2049890/app.To-Do.Items.fix.attempt.txt)

Thanks!

**Comment by maltehi** [comment]
Fixed that with the newest commit. Flagged mails can't be moved across lanes yet, though. This would require assigning them a status somehow... Maybe later.

**Comment by pinosdave** [comment]
Thanks Malte for all the work on this! I didn't think it would be as complex as this.

I attempted to implement your changes, but now my Backlog column is blank now. I removed the journal entries in outlook, so they could be regenerated, but still continued blank. I also set /"INCLUDE_TODOS": true,/ and still was nothing showed up. I tested it on the Next column and it worked on that column, just not the Backlog column. I'm using Outlook 2016 if that makes any difference.

Thanks,
Dave

**Comment by pinosdave** [comment]
Thanks for the input Malte! I changed this in the config and was able to restore functionality for the Backlog lane:
    "DEFERRED": {
      "VALUE": 0,
      "TEXT": "Not Started"
    }

**Comment by pinosdave** [comment]
Malte,
Thanks for the changes that you had made and the amount of work you've already put into this. As I was working on the newest version you deployed, I had a couple questions.

I'm finding that all flagged emails show up in the Backlog lane including the ones that have been marked as completed. How can I apply a filter that would only show emails that were flagged, but not in a completed status?

Like you had mentioned previously, dragging emails to other lanes does not work correctly. In the previous version by Evren, a flagged email that was dragged to another lane was converted into a task. Is that something that could be brought back until a better solution for handling emails is developed?

Thanks again for all the development time you've put into this. I hope these two changes aren't too complicated to develop.

Dave

**Comment by Smittyman** [comment]
Malte,

I would definitely be interested in seeing the project support flagged emails in some fashion.  If there were some way to keep the flagged emails in their current state with the ability to display the due date associated with the flag on a card that could move between lanes that would be great.  I'm speaking strictly from a workflow perspective, but you can use quick steps in outlook to flag an email and drop it in another folder rather than having to move it to a task folder and fill out all the other fields.  I do utilize tasks that are pulled in from OneNote as well though, so having my flagged emails and tasks in the same Kanban board would be a huge step up in visualization of all my work.  Anyway, thanks for all the hard work on the project fork and I look forward to seeing it continue to evolve.  Thanks.

Mike

**Comment by pinosdave** [comment]
Hey Malte,
Sorry for not getting back to you sooner. I was using the last version of evrenvarol's taskboard. From my testing with this version of taskboard, I found that when I move the email from the Backlog lane to the Next lane, it automatically converts it into a task and actually places the email in the deleted items. The task is still kept and placed in the Next lane. Hope that helps some.

Thanks,
Dave

**Comment by NewMC** [comment]
Thanks all for the good work on this, I can confirm full functionality on Windows 7 (64-bit) with MS Office Pro Plus 2013 (32-bit).  I used the method where I replaced my home page location for my main account folder, but also works in IE and Chrome (with IE Tab extension) once ActiveX controls are enabled.

A couple things I've noticed, and I'm sure I can probably modify for my needs, just either haven't found the setting or dove into the code yet.

1) If you turn off the 'Next' folder you do not see new tasks.  I do not use Next so I've changed the title of Next to In Progress and disabled the In Progress folder.  What determines the default folder where new tasks are created or sorted to by default?

2) There is some unexpected behavior with the duedate sort.  If sorted in descending order it places tasks with no due date first, but then places nearer due dates to the bottom of the list.  If sorting in ascending order it places tasks with nearer due dates to the bottom of the list, and any tasks that do not have a due date assigned last.  The descending order sort is preferred in my case, but how can I put tasks that do not have an assigned due date to the bottom of the list?  In other words, I'm looking to add or modify an existing filter that always places tasks with no assigned due date to the bottom of the list.

3) Off topic (Outlook specific): Do you happen to know of a switch/setting in Outlook that will permanently allow access, so that you can avoid the frequent "Allow access" notification?  By default, the maximum duration that can be allowed is 10 minutes, at which time you must approve again.

**A note regarding dragging of emails to the Outlook Tasks folder:  My experience is that I typically lose all formatting with this method.  Any embedded images, tables or attachments are not transferred to the new task that gets created, and text formatting gets changed.  A good alternative, at least for work emails that may contain more than simple text, is to create a new Quick Step that uses the "Create a task with attachment" action.  This will place the original email with all attachments and formatting in a new task, as an attachment.

Thanks again!  This will really streamline my workflow and I've already eliminated the Meistertask, Notion.so, and OneNote kanban boards that I was using.

**Comment by Runecreed** [comment]
This feature would be great as the Kanban board really should have drag functionality as well as showing all outstanding tasks in the backlog. As it stands without showing all tasks (the Tasks folder is really just a subset of all tasks if you use other folders to organize via project for example) its a bit incomplete.

I'm quite busy with work these days so probably won't be able to chime in for the near future- this is very promising stuff though and would love to see the project continued. 

I think it has a very promising workflow should the board view allow for flagged emails + other subfolders to be scanned and added to the backlog lane -- I imagine dragging an email from one lane to another would be doable by creating a task out of it with attachment of the original, and unflagging the original; that would clear it from the backlog lane with appropriate task delegated to another one, perhaps.

Thanks for the hard work, I'm really happy to have found this project!

**Comment by maphew** [comment]
Can anyone provide a concrete example of how ToDo items can be made to show up? I tried adding `INCLUDE_TODOS` as per the below but there is noticeable change.

```
 "BACKLOG_FOLDER": {
    "ACTIVE": true,
    "INCLUDE_TODOS": true,
    "NAME": "",
    "TITLE": "BACKLOG",
    "SORT": "-priority,duedate,categoryNames,subject",
    "RESTRICT": "",
    "DISPLAY_PROPERTIES": {
      "OWNER": false,
      "PERCENT": false,
      "TOTALWORK": false
    },
    "FILTER_ON_START_DATE": false,
    "REPORT": {
      "DISPLAY": true
    }
  }
```
I'm using commit 63c5376e2648da2a40515dff872faa743148b414 (HEAD -> master, origin/master, origin/HEAD).

**Comment by maphew** [comment]
Ok, I figured out my mistake and learned a couple things: 

* the INCLUDE_TODOS setting isn't per container of _Backlog, Next, ..._ , but a single global setting. It is found near the bottom of the config file, around line 95.

* The next line `"INCLUDE_TODOS_STATUS": 0,`: the number corresponds to the items in the `"STATUS"` json block. Out of the box this means the _Backlog_ lane is empty, and _Next_ is where all the ToDo's show up. To put the ToDo's in _Backlog_ lane use status of **4** (gleaned from @03nix and @Runecreed above).

* to make editing the config less error prone use Notepad++ with the JSON Viewer plugin, and test in something like https://jsonlint.com/ if you can't find any errors being complained about.

Here's my working config: https://gist.github.com/maphew/2ab0f4d0c7fa2d0ab86e8fa997308071
